import React from 'react';
import './ResumeBuilder.css';
//import resumeImage from './dummyResumeCraft.png'; // Replace with your image path
import 'font-awesome/css/font-awesome.min.css';

const ResumeBuilder = () => {
    return (
        <div className="resume-builder">
            <div className="image-section">
                <img src="https://jobswithrelocareerservices.com/wp-content/uploads/2024/06/Asset-31EER-1024x962.png" alt="Resume previews" style={{ height: "300px" }} />
            </div>

            <div className="text-section">
                <h1>IMPRESSIVE RESUMES</h1>
                <h2>EASY ONLINE BUILDER</h2>
                <ul className='list'>
                    <li>
                        <i className="fa fa-check"></i>
                        Professional out-of-the-box resumes, instantly generated by the most advanced resume builder technology available.

                    </li>
                    <li>
                        <i className="fa fa-check"></i>
                        Effortless crafting. Real-time preview & pre-written resume examples.
                        Dozens of HR-approved resume templates.

                    </li>
                    <li>
                        <i className="fa fa-check"></i>
                        Land your dream job with the perfect resume employers are looking for!

                    </li>
                </ul>
            </div>
        </div>
    );
};

export default ResumeBuilder;
